export const factoryAbi = [
  {
    type: 'function',
    name: 'feeTo',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'feeToSetter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'getPair',
    stateMutability: 'view',
    inputs: [
      { name: 'tokenA', type: 'address' },
      { name: 'tokenB', type: 'address' },
    ],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'allPairs',
    stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'allPairsLength',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createPair',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'tokenA', type: 'address' },
      { name: 'tokenB', type: 'address' },
    ],
    outputs: [{ name: 'pair', type: 'address' }],
  },
  {
    type: 'function',
    name: 'etx',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'pairCreationFee',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'trustedCreators',
    stateMutability: 'view',
    inputs: [{ name: 'creator', type: 'address' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'setFeeTo',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_feeTo', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFeeToSetter',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_feeToSetter', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setTrustedCreator',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'creator', type: 'address' },
      { name: 'trusted', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setPairCreationFee',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'fee', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'event',
    name: 'PairCreated',
    inputs: [
      { indexed: true, name: 'token0', type: 'address' },
      { indexed: true, name: 'token1', type: 'address' },
      { indexed: false, name: 'pair', type: 'address' },
      { indexed: false, name: '', type: 'uint256' },
    ],
  },
] as const;
